.PHONY: clean All

All:
	@echo "----------Building project:[ Week1_opdracht2 -  ]----------"
	@cd "Week1_opdracht2" && "$(MAKE)" -f  "Week1_opdracht2.mk"
clean:
	@echo "----------Cleaning project:[ Week1_opdracht2 -  ]----------"
	@cd "Week1_opdracht2" && "$(MAKE)" -f  "Week1_opdracht2.mk" clean
